### ISSUE TITLE
welch_test()

### ISSUE THREAD

**Issue by Zhe-JJ-Wang** [brielin/WWER#1]
Hi Brielin ,

Thank you for developing such cool method. I'm trying to use your WWER package, but encountered some problems. 

In the README file, it seems like welch_test() used betas for both exposure and outcome from sample 1 (copied from README as below). 

# beta_exp_1, se_exp_1: exposure effects and SEs, sample 1.
# beta_exp_2, se_exp_1: exposure effects and SEs, sample 2.
# beta_out_1, se_out_1: outcome effects and SEs, sample 1.
# beta_out_2, se_out_2: outcome effects and SEs, sample 2.
weights = WWER::welch_test(beta_exp_1, beta_out_1, se_exp_1, se_out_1)$t

But actually in the code (WWER.R) when you defined welch_test() function, it seems like the it use beta2 and beta1 that comes from both sample 1 and sample 2 (as below):

#' @param beta1 Float or vector of floats, mean of the first sample.
#' @param beta2 Float or vector of floats, mean of the second sample.
#' @param se1 Float or vector of floats, SD of estimate of mu1.
#' @param se2 Float or vector of floats, SD of estimate of mu2.
#' @param welch_thresh Float, p_value threshold for significance.
#' @export
welch_test <- function(beta2, beta1, se2, se1, welch_thresh = 0.05) {...

Do you mind clarifing what is the correct one to use?

Additionally, I was wondering if you could provide more documentation about the results from fit_tce(), like how to interpret the matrix? For example, if I got a R_tce matrix as below. Then the 0.04 is the R_tce from A->B or B->A?
      A    B
A   1    0.04
B   -0.01  1

Thanks and look forward to your answer.

Best,
Zhe

**Comment by brielin** [comment]
Hi Zhe,

I am very sorry for the delay in responding to this. I saw it but was working on other things and forgot to get back to it later.

I agree this is confusing. In the doc for the welch_test() function, sample 1 and sample 2 refer to the pair of phenotypes (exposure and outcome) and not the split data. So they are both technically correct, just badly worded. I will make an update to fix this documentation in a minute. 

For your second question, the rows are the exposure and columns are outcomes. So the 0.04 is A -> B. I will update the docs to reflect this as well.

Let me know if you have any other questions and I'll try to respond in a more timely manner next time.

Brielin

**Comment by brielin** [comment]
So looking at the code again, I realize I'm not using exposure and outcome there because the calculation is symmetric (at that step, there is no distinguishing which is the exposure or outcome). I've left the variable names as is and updated the documentation to note that these are phenotypes and not the split sample.
